#### Numpy:Play with Array(numbers)
#### Pandas:Dataset
#### Matbplotlib:Data visualisation
#### Seaborn:Data visuallisation
#### Scipy:Statistical
#### Skllearn:Algorithm

# NUMPY:
### Package for Mqultiple Array

In [20]:
import numpy as np

In [21]:
simple_list=[6,9,4]
np.array(simple_list)

array([6, 9, 4])

In [22]:
arr=np.array([1,2,4])
arr

array([1, 2, 4])

In [23]:
list_of_lists=[[1,3,5],[1,3,6],[2,6,8]]
np.array(list_of_lists)

array([[1, 3, 5],
       [1, 3, 6],
       [2, 6, 8]])

In [24]:
np.arange(2,14)                             # arrange always ends with one less than last number

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
np.arange(1,22,5)                           # difference 5

array([ 1,  6, 11, 16, 21])

In [27]:
np.arange(8)                                # starts with 0

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.zeros(3)                                  #list of n zeros  with decimal

array([0., 0., 0.])

In [35]:
np.zeros(4,int)                              #list of n of zeros without decimal

array([0, 0, 0, 0])

In [40]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.zeros((2,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
np.linspace(0,2,7)                                     

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [43]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [44]:
np.random.rand(3,5)

array([[0.47827074, 0.83679812, 0.70860241, 0.7852581 , 0.33431672],
       [0.49989366, 0.05498843, 0.7454194 , 0.41336257, 0.21023811],
       [0.02853994, 0.5486188 , 0.35028846, 0.59717087, 0.8784506 ]])

In [46]:
arr=np.random.randn(2,4)
arr

array([[-2.03674985,  0.35239155, -0.1495597 ,  1.18234959],
       [-0.8226781 , -0.31430926, -0.06605669, -0.67433557]])

In [48]:
np.random.randint(2,100)

56

In [49]:
np.random.randint(20,57,100)

array([41, 33, 48, 42, 28, 46, 32, 26, 49, 50, 45, 49, 48, 33, 53, 49, 42,
       50, 26, 27, 38, 41, 56, 53, 23, 30, 38, 55, 55, 23, 21, 46, 30, 20,
       20, 35, 33, 31, 52, 44, 51, 20, 23, 41, 20, 24, 45, 32, 25, 43, 32,
       20, 25, 30, 30, 21, 45, 40, 20, 55, 49, 51, 43, 35, 25, 37, 50, 51,
       46, 27, 54, 29, 20, 24, 52, 41, 37, 54, 41, 44, 38, 49, 37, 46, 27,
       48, 40, 22, 22, 34, 53, 29, 22, 34, 51, 50, 43, 21, 28, 27])

In [52]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
rand_array=np.random.randint(0,10,50)
rand_array

array([7, 6, 6, 9, 5, 1, 7, 9, 7, 2, 8, 1, 8, 2, 9, 7, 0, 9, 3, 7, 4, 3,
       6, 0, 5, 7, 1, 5, 4, 8, 2, 7, 1, 3, 9, 3, 7, 8, 2, 6, 6, 0, 6, 5,
       0, 7, 1, 0, 4, 0])

In [56]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [57]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [58]:
rand_array.max()

9

In [60]:
rand_array.argmax()

3

In [62]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
a=np.random.rand(2,3)
a

array([[0.96352472, 0.46522849, 0.31487278],
       [0.05499704, 0.33147168, 0.32541678]])

In [66]:
a.T

array([[0.96352472, 0.05499704],
       [0.46522849, 0.33147168],
       [0.31487278, 0.32541678]])

In [67]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
sample_array[0]

10

In [69]:
sample_array[2:5]

array([12, 13, 14])

In [72]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [74]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [79]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [81]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

## TWO Dimensinal Array

In [82]:
import numpy as np

In [83]:
sample_matrix=np.array([[20,56,50,69],[25,58,78,55],[57,78,45,78]])
sample_matrix

array([[20, 56, 50, 69],
       [25, 58, 78, 55],
       [57, 78, 45, 78]])

In [84]:
sample_matrix[1,2]

78

In [85]:
sample_matrix[2,:]

array([57, 78, 45, 78])

In [86]:
sample_matrix[2]

array([57, 78, 45, 78])

In [88]:
sample_matrix[:,(3,2)]                      # :->all rows 3->column 2->column

array([[69, 50],
       [55, 78],
       [78, 45]])

## Selection Techniques

In [97]:
sample_array=np.arange(1,20)
sample_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [98]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [99]:
np.exp(sample_array)                       #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [100]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [101]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [102]:
np.max(sample_array)

19

In [103]:
np.min(sample_array)

1

In [105]:
np.argmax(sample_array)

18

In [106]:
np.argmin(sample_array)

0

In [107]:
np.std(sample_array)

5.477225575051661

In [108]:
np.var(sample_array)

30.0

In [109]:
np.mean(sample_array)

10.0

In [111]:
array=np.random.randn(3,4)
array

array([[-0.55886094,  0.46276666,  0.74196993,  1.05699333],
       [ 2.08693533, -0.53453818,  0.56904337,  1.63708388],
       [-0.62553181, -0.36911684,  0.74572453, -0.83144225]])

In [112]:
np.round(array,decimals=2)

array([[-0.56,  0.46,  0.74,  1.06],
       [ 2.09, -0.53,  0.57,  1.64],
       [-0.63, -0.37,  0.75, -0.83]])

In [114]:
sports=np.array(['golf','cricket','fball','soccer'])
np.unique(sports)

array(['cricket', 'fball', 'golf', 'soccer'], dtype='<U7')

# PANDAS:
### for Dataset

In [115]:
import pandas as pd
import numpy as np

## Pandas Dataframe And Indexing

In [129]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','tennis'])
sports1

cricket       1
football      2
basketball    3
tennis        4
dtype: int64

In [130]:
sports1['tennis']

4

In [131]:
sports2=pd.Series([13,27,38,54],index=['cricket','football','basketball','hockey'])
sports2

cricket       13
football      27
basketball    38
hockey        54
dtype: int64

In [132]:
sports1+sports2

basketball    41.0
cricket       14.0
football      29.0
hockey         NaN
tennis         NaN
dtype: float64

In [135]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.876169  0.451823  0.518042  0.743040  0.987373
B  0.891900  0.194191  0.642284  0.489777  0.154393
C  0.739129  0.801403  0.909558  0.761088  0.037490
D  0.350443  0.156609  0.787793  0.278802  0.945882
E  0.564766  0.960777  0.346551  0.359155  0.160382
F  0.439543  0.181693  0.317010  0.082096  0.321694
G  0.081262  0.584169  0.246760  0.778361  0.062946
H  0.581545  0.110409  0.766126  0.592323  0.049842

In [137]:
df1["Score1"]

A    0.876169
B    0.891900
C    0.739129
D    0.350443
E    0.564766
F    0.439543
G    0.081262
H    0.581545
Name: Score1, dtype: float64

In [140]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.876169  0.451823  0.518042
B  0.891900  0.194191  0.642284
C  0.739129  0.801403  0.909558
D  0.350443  0.156609  0.787793
E  0.564766  0.960777  0.346551
F  0.439543  0.181693  0.317010
G  0.081262  0.584169  0.246760
H  0.581545  0.110409  0.766126

In [143]:
df1["Score6"]=df1["Score3"]+df1["Score1"]
df1                                

Score1    Score2    Score3    Score4    Score5    Score6
A  0.876169  0.451823  0.518042  0.743040  0.987373  1.394211
B  0.891900  0.194191  0.642284  0.489777  0.154393  1.534184
C  0.739129  0.801403  0.909558  0.761088  0.037490  1.648687
D  0.350443  0.156609  0.787793  0.278802  0.945882  1.138236
E  0.564766  0.960777  0.346551  0.359155  0.160382  0.911317
F  0.439543  0.181693  0.317010  0.082096  0.321694  0.756552
G  0.081262  0.584169  0.246760  0.778361  0.062946  0.328022
H  0.581545  0.110409  0.766126  0.592323  0.049842  1.347671

In [172]:
df1.drop('H')                                # deletion of row

Score1    Score2    Score3    Score4    Score5    Score6
A  0.876169  0.451823  0.518042  0.743040  0.987373  1.394211
B  0.891900  0.194191  0.642284  0.489777  0.154393  1.534184
C  0.739129  0.801403  0.909558  0.761088  0.037490  1.648687
D  0.350443  0.156609  0.787793  0.278802  0.945882  1.138236
E  0.564766  0.960777  0.346551  0.359155  0.160382  0.911317
F  0.439543  0.181693  0.317010  0.082096  0.321694  0.756552
G  0.081262  0.584169  0.246760  0.778361  0.062946  0.328022

In [165]:
df2={'ID':['101','102','103','135','155'],'Name':['Jeevith','Adil','Priyesh','Ankit','Harsh'],'Profit':[100,154,76,123,85]}
df=pd.DataFrame(df2)
df

ID     Name  Profit
0  101  Jeevith     100
1  102     Adil     154
2  103  Priyesh      76
3  135    Ankit     123
4  155    Harsh      85

In [166]:
df["ID"]

0    101
1    102
2    103
3    135
4    155
Name: ID, dtype: object

In [167]:
df[["ID","Name"]]

ID     Name
0  101  Jeevith
1  102     Adil
2  103  Priyesh
3  135    Ankit
4  155    Harsh

In [168]:
df=df.drop("ID",axis=1)       #deletion of column

In [163]:
df

Name  Profit
0  Jeevith     100
1     Adil     154
2  Priyesh      76
3    Ankit     123
4    Harsh      85

In [169]:
df.drop(3)

Name  Profit
0  Jeevith     100
1     Adil     154
2  Priyesh      76
4    Harsh      85